"""
Django settings for luna_backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import requests
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-7$y7%dqk8gm)_lv02l+qkmp^dpbv-=q5r9(z)slf&94ubfw7b=")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["31ada3e8611d4e04b2dcd8532c5c4c6b.vfs.cloud9.us-east-1.amazonaws.com",
    "lunaenv.eba-2d2e2juu.us-east-1.elasticbeanstalk.com",
    "localhost",
    "127.0.0.1",
    ".elasticbeanstalk.com",
    # "172.31.14.232",
    ]
try:
    EC2_IP = requests.get(
        'http://169.254.169.254/latest/meta-data/local-ipv4',
        timeout=0.5
    ).text
    ALLOWED_HOSTS.append(EC2_IP)
except Exception:
    pass
import ssl
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_celery_results',
    'users',
    'reminders',
    'shopping',
    'assistant',
    'frontend',
]

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "frontend" / "static",]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Create an SSL context that accepts AWS TLS without verification (for dev)
REDIS_SSL_CONTEXT = ssl.create_default_context()
REDIS_SSL_CONTEXT.check_hostname = False
REDIS_SSL_CONTEXT.verify_mode = ssl.CERT_NONE
_redis_base_url = os.getenv(
    "CELERY_BROKER_URL",
    "rediss://lunaredis-dnl0wr.serverless.use1.cache.amazonaws.com:6379"
)

# Append ssl_cert_reqs=CERT_NONE to satisfy the rediss:// URL validator
def _add_ssl_param(url: str) -> str:
    sep = "&" if "?" in url else "?"
    return f"{url}{sep}ssl_cert_reqs=CERT_NONE"
CELERY_BROKER_URL = _add_ssl_param(os.getenv("CELERY_BROKER_URL", "rediss://lunaredis-dnl0wr.serverless.use1.cache.amazonaws.com:6379"))
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_TASK_TRACK_STARTED = True
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'is_cluster': True,
    'retry_on_timeout': True,
    'ssl': {
        'ssl_cert_reqs': ssl.CERT_NONE,
        'ssl_context': REDIS_SSL_CONTEXT,
    }
}
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
    'is_cluster': True,
    'ssl': {
        'backend_use_ssl': ssl.CERT_NONE,
        'ssl_context': REDIS_SSL_CONTEXT,
    }
}
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "300"))
CELERY_TASK_ALWAYS_EAGER = env_bool("CELERY_TASK_ALWAYS_EAGER", False)
CELERY_TASK_STORE_EAGER_RESULT = env_bool("CELERY_TASK_STORE_EAGER_RESULT", False)
CITY_INFO_API_URL = os.getenv(
    "CITY_INFO_API_URL",
    "https://mec2nt9daf.execute-api.us-east-1.amazonaws.com/default/GeoCodingCityInfo",
)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_EXTENDED = True
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    "https://lunaenv.eba-2d2e2juu.us-east-1.elasticbeanstalk.com",
    "http://lunaenv.eba-2d2e2juu.us-east-1.elasticbeanstalk.com",
]
ROOT_URLCONF = 'luna_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'luna_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'luna',
#         'USER': 'postgres',
#         # 'PASSWORD': 'ronak',
#         'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
#         'HOST': '127.0.0.1', #can deploy it on aws
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
