"""
Django settings for luna_backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-7$y7%dqk8gm)_lv02l+qkmp^dpbv-=q5r9(z)slf&94ubfw7b=")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        # Local + wildcards for free tunnels (Cloudflare / ngrok) so any tunnel
        # URL works without reconfiguring. Leading dot = match all subdomains.
        "localhost,127.0.0.1,.trycloudflare.com,.ngrok-free.app,.ngrok-free.dev,.ngrok.io,.ngrok.app",
    ).split(",")
    if h.strip()
]
# Render sets this automatically to the service's public hostname.
_render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if _render_host:
    ALLOWED_HOSTS.append(_render_host)
# Railway exposes the public domain of the service here.
_railway_host = os.getenv("RAILWAY_PUBLIC_DOMAIN")
if _railway_host:
    ALLOWED_HOSTS.append(_railway_host)
# Allow any Railway subdomain by default too (harmless; hosts still need a valid cert).
if ".up.railway.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".up.railway.app")

from dotenv import load_dotenv

load_dotenv()

# --- LLM providers -------------------------------------------------------- #
# Cost model (see docs/ROADMAP_SCALE.md): users can bring their own API key
# (premium), everyone else uses the owner-hosted FREE model. Casual talk always
# uses the free model. See assistant/services/providers.py.
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")  # owner key: optional free fallback
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "models/gemini-2.5-flash")

# Free Hugging Face LLM for casual conversation / light tasks.
HF_API_TOKEN = os.getenv("HF_API_TOKEN", "")
HF_MODEL = os.getenv("HF_MODEL", "Qwen/Qwen2.5-7B-Instruct")

# Groq free tier — fast, capable model for keyless users. Optional; if unset the
# free tier falls back to Hugging Face, then the owner's Gemini.
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

# Let keyless users fall back to the owner's Gemini key. Fine for personal/dev use;
# set false at scale so the owner isn't billed for every user.
FREE_LLM_ALLOW_OWNER_GEMINI = env_bool("FREE_LLM_ALLOW_OWNER_GEMINI", True)
# Daily free-model calls per user. 0 = unlimited (default; enforce by raising it).
FREE_LLM_DAILY_QUOTA = int(os.getenv("FREE_LLM_DAILY_QUOTA", "0"))

# Agentic tool-loop (assistant/services/agent.py). Off by default: deterministic
# commands always use the no-LLM fast path; when enabled, reasoning-heavy commands
# use the multi-step agent (falls back to the classic pipeline on any failure).
ENABLE_AGENT = env_bool("ENABLE_AGENT", False)

# Key used to encrypt users' BYO API keys at rest. Falls back to SECRET_KEY; set a
# dedicated value in production and rotate it independently.
LUNA_ENCRYPTION_KEY = os.getenv("LUNA_ENCRYPTION_KEY", "")

# --- Cache / Redis -------------------------------------------------------- #
# Redis in production (quota counters, shared conversation memory later); local
# in-memory cache in dev when REDIS_URL is unset.
REDIS_URL = os.getenv("REDIS_URL", "")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}
    }

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_celery_results',
    'users',
    'reminders',
    'shopping',
    'assistant',
    'frontend',
]

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "frontend" / "static",]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL") or os.getenv("REDIS_URL") or "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "django-db")
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "300"))
CELERY_TASK_ALWAYS_EAGER = env_bool("CELERY_TASK_ALWAYS_EAGER", False)
CELERY_TASK_STORE_EAGER_RESULT = env_bool("CELERY_TASK_STORE_EAGER_RESULT", False)
# NOTE: The original City Info API was an AWS Lambda that has been decommissioned
# (the lab expired). It is left configurable so an alternative can be plugged in,
# but the assistant no longer depends on it. Leave empty to disable city lookups.
CITY_INFO_API_URL = os.getenv("CITY_INFO_API_URL", "")

# News: Google News RSS needs no API key. {query} is URL-encoded search terms.
NEWS_RSS_URL = os.getenv(
    "NEWS_RSS_URL",
    "https://news.google.com/rss/search?q={query}&hl=en-US&gl=US&ceid=US:en",
)
CELERY_RESULT_EXTENDED = True
NEWS_TOP_RSS_URL = os.getenv(
    "NEWS_TOP_RSS_URL",
    "https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en",
)

# Timezone used when the assistant reports the current time to the user.
ASSISTANT_TIMEZONE = os.getenv("ASSISTANT_TIMEZONE", "UTC")

# Whisper model for command transcription. "base.en" is a good accuracy/speed
# balance on CPU; "small.en" is more accurate but ~2x slower.
WHISPER_MODEL = os.getenv("WHISPER_MODEL", "base.en")
# Whisper needs ~1GB+ RAM; disable on small hosts (the extension's mic button
# still gives accurate speech-to-text client-side via the Web Speech API).
ENABLE_WHISPER = env_bool("ENABLE_WHISPER", True)
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# The extension calls from a chrome-extension:// origin (dynamic), so allow all
# origins for the API. Auth is via JWT Bearer tokens, not cookies.
CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]
if _render_host:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_render_host}")
if _railway_host:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_railway_host}")

# Behind Render's TLS-terminating proxy.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

ROOT_URLCONF = 'luna_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'luna_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'luna',
#         'USER': 'postgres',
#         # 'PASSWORD': 'ronak',
#         'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
#         'HOST': '127.0.0.1', #can deploy it on aws
#         'PORT': '5432',
#     }
# }

import dj_database_url

# Uses DATABASE_URL when set (Render Postgres); falls back to local sqlite.
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
