# Generated by Django 6.0.2 on 2026-07-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_shoppingitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
